"""latest 1

Revision ID: 05760a0f6c6e
Revises: 5597d0c25508
Create Date: 2021-01-04 00:34:35.100276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05760a0f6c6e'
down_revision = '5597d0c25508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_drawings', 'x_drawing_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_drawings', sa.Column('x_drawing_part', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
