"""Add a new column to part

Revision ID: 16c8008449df
Revises: 55862722a23f
Create Date: 2021-01-03 20:25:40.957832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c8008449df'
down_revision = '55862722a23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_drawings', sa.Column('part_drawing_score', sa.String(length=5), nullable=True))
    op.add_column('parts', sa.Column('part_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'part_score')
    op.drop_column('part_drawings', 'part_drawing_score')
    # ### end Alembic commands ###
