"""Initialize my local db

Revision ID: 3b41f3e98254
Revises: 5d028b75242a
Create Date: 2020-12-28 22:12:28.299446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b41f3e98254'
down_revision = '5d028b75242a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
