"""Delete column vendor_desc from vendors

Revision ID: 43eb3bd83a76
Revises: eaf420375f5a
Create Date: 2021-01-02 00:45:45.372445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eb3bd83a76'
down_revision = 'eaf420375f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'vendor_desc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
