"""Changing 3 tables

Revision ID: 55862722a23f
Revises: 43eb3bd83a76
Create Date: 2021-01-02 16:06:39.472990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55862722a23f'
down_revision = '43eb3bd83a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_drawings', sa.Column('part_drawing_score', sa.String(length=5), nullable=True))
    op.add_column('vendors', sa.Column('vendor_score', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'vendor_score')
    op.drop_column('part_drawings', 'part_drawing_score')
    # ### end Alembic commands ###
