"""Lates

Revision ID: 5597d0c25508
Revises: 16c8008449df
Create Date: 2021-01-03 21:30:38.214878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5597d0c25508'
down_revision = '16c8008449df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_drawings', sa.Column('x_drawing_part', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_drawings', 'x_drawing_part')
    # ### end Alembic commands ###
