"""Adding a new column to class Parts

Revision ID: 5d028b75242a
Revises: 1ced9c0cbbca
Create Date: 2020-12-28 19:42:42.648149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5d028b75242a'
down_revision = '1ced9c0cbbca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('part_desc', sa.String(length=255), server_default='Hi',
                                     nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'part_desc')
    # ### end Alembic commands ###
