"""Making the source db in line with the local db

Revision ID: d7925de01048
Revises: 94b5150c1d4f
Create Date: 2020-12-28 22:40:53.552070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7925de01048'
down_revision = '94b5150c1d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('part_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parts', 'part_score')
    # ### end Alembic commands ###
