"""Add a new column to vendors called vendors_desc

Revision ID: eaf420375f5a
Revises: d7925de01048
Create Date: 2021-01-01 23:11:07.178415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaf420375f5a'
down_revision = 'd7925de01048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'vendor_desc')
    # ### end Alembic commands ###
